apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tommytest3
spec:
  replicas: 4
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - myapp1
          - myapp
  template:
    metadata:
      labels:
        name: tommytest3
        app: myapp1
    spec:
      containers:
      - image: tomcat
        name: tomcat1
