apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tommytest3
spec:
  replicas: 4
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - myapp1
          - myapp
      - key: type
        operator: NotIn
        values:
           - frontend
  template:
    metadata:
      labels:
        app: myapp
        type: backend
    spec:
      containers:
      - image: tomcat
        name: tomcat1
