apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: dtestdeploy
  name: dtestdeploy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp
  type: NodePort
status:
  loadBalancer: {}
