apiVersion: v1
kind: Pod
metadata:
  name: apachetestyml3
  #namespace: demotest
spec:
  containers:
  - image: tomcat
    name: apachetestyml
    imagePullPolicy: Never
    envFrom:
      - configMapRef:
          name: cm5
