apiVersion: v1
kind: Pod
metadata:
  name: apachetestyml3
  #namespace: demotest
spec:
  containers:
  - image: tomcat
    name: apachetestyml
    imagePullPolicy: Never
    env:
      - name: kahipan
        valueFrom:
          secretKeyRef:
            key: database_ip
            name: sc1
